#!/bin/sh

# 1) Include files with required values are provided in the ./include/ folder.

# 2) CCPGATE:

# Run with the following commands to reproduce the reference outputs 'vmc_optall.out':
cd TZ_1M_128
mpirun -np 24 -s all ~/software/champ-development/bin/vmc.mov1 < vmc_optall.inp > test.out
cd ..

# prepare machinefile to run on 5 nodes with 24 processes each
cd TZ_1M_5114
mpirun -ppn 24 -machinefile machinefile -s all ~/software/champ-development/bin/vmc.mov1 < vmc_optall.inp > test.out
cd ..

# prepare machinefile to run on 10 nodes with 24 processes each
cd TZ_1M_32768
mpirun -ppn 24 -machinefile machinefile -s all ~/software/champ-development/bin/vmc.mov1 < vmc_optall.inp > test.out
cd ..


# 3) Cartesius:

# - Only statistical results can be compared to jobs from ccpgate. The first few steps of the sampling are usually identical if the same number of processes (24, 120 and 240) are used.

# example submit script:
#!/bin/bash
#SBATCH -t 20:00
#SBATCH -N 1
#SBATCH --ntasks-per-node 24
#SBATCH -p short
#srun ~/software/champ-development/bin/vmc.mov1 < vmc_optall.inp > test.out
