## Know the architecture of the CPU and set compile flags accordingly
set(TARGET_ARCHITECTURE "generic")
set(CHAMP_COMPILE_DEFINITIONS "")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  file(READ "/proc/cpuinfo" _cpuinfo)
  string(REGEX REPLACE ".*\nflags[ \t]*:[ \t]+([^\n]+).*" "\\1" _cpu_flags "${_cpuinfo}")
endif()

if(NOT DEFINED VECTORIZED)
  set(VECTORIZED "")
endif()
string(TOLOWER "${VECTORIZED}" VECTORIZED)
message(STATUS "Vectorization status  " ${VECTORIZED})


if(VECTORIZED STREQUAL "portable-avx2")
  message(STATUS "Vectorization: Forcing portable AVX2 (CI/Release mode)")

  if(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
    # 'haswell' is the safest baseline for AVX2/FMA on Linux
    list(APPEND Fortran_FLAGS "-march=haswell")
  elseif(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
    list(APPEND Fortran_FLAGS "-march=core-avx2")
  elseif(CMAKE_Fortran_COMPILER_ID MATCHES "Flang")
    list(APPEND Fortran_FLAGS "-march=x86-64-v3")
  else()
    list(APPEND Fortran_FLAGS "-axCORE-AVX2")
  endif()

  set(TARGET_ARCHITECTURE "avx2")
  list(APPEND CHAMP_COMPILE_DEFINITIONS VECTORIZATION="avx2")

elseif(VECTORIZED STREQUAL "yes")
  message(STATUS "Vectorization switched ON by user  ")

  if(_cpu_flags MATCHES "avx512")
    if(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
      list(APPEND Fortran_FLAGS "-axCORE-AVX512")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
      list(APPEND Fortran_FLAGS "-march=native")
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Flang")
      list(APPEND Fortran_FLAGS "-march=native")
    else()
      list(APPEND Fortran_FLAGS "-axCORE-AVX512")
    endif()
    set(TARGET_ARCHITECTURE "avx512")
    list(APPEND CHAMP_COMPILE_DEFINITIONS VECTORIZATION="avx512")
  elseif(_cpu_flags MATCHES "avx2")
    if(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
      list(APPEND Fortran_FLAGS "-march=core-avx2")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
      list(APPEND Fortran_FLAGS "-march=native")
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Flang")
      list(APPEND Fortran_FLAGS "-march=native")
    else()
      list(APPEND Fortran_FLAGS "-axCORE-AVX2")
    endif()
    set(TARGET_ARCHITECTURE "avx2")
    list(APPEND CHAMP_COMPILE_DEFINITIONS VECTORIZATION="avx2")
  endif()

elseif(VECTORIZED STREQUAL "auto")
  message(STATUS "Vectorization is auto; built-in vectorization used but no code-selection (loop modification) done  ")
  list(APPEND Fortran_FLAGS "-xCORE-AVX512")
  set(TARGET_ARCHITECTURE "avx512")
elseif(VECTORIZED STREQUAL "no")
  message(STATUS "Vectorization switched off by user  ")
else()
  message(STATUS "Vectorization is default  ")
  if(_cpu_flags MATCHES "avx512")
    if(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
      list(APPEND Fortran_FLAGS "-axCORE-AVX512")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
      list(APPEND Fortran_FLAGS "-march=native")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC")
      list(APPEND Fortran_FLAGS "-Mvect")
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Flang")
      list(APPEND Fortran_FLAGS "-march=native")
    else()
      list(APPEND Fortran_FLAGS "-axCORE-AVX512")
    endif()
    set(TARGET_ARCHITECTURE "avx512")
    list(APPEND CHAMP_COMPILE_DEFINITIONS VECTORIZATION="avx512")
  elseif(_cpu_flags MATCHES "avx2")
    if(CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
      list(APPEND Fortran_FLAGS "-march=core-avx2")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
      list(APPEND Fortran_FLAGS "-march=native")
    elseif(CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC")
      list(APPEND Fortran_FLAGS "-Mvect")
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Flang")
      list(APPEND Fortran_FLAGS "-march=native")
    else()
      list(APPEND Fortran_FLAGS "-axCORE-AVX2")
    endif()
    set(TARGET_ARCHITECTURE "avx2")
    list(APPEND CHAMP_COMPILE_DEFINITIONS VECTORIZATION="avx2")
  endif()
endif()
unset(VECTORIZED CACHE)

list(APPEND CHAMP_COMPILE_DEFINITIONS TARGET_ARCHITECTURE="${TARGET_ARCHITECTURE}")
