version: 2
jobs:
  build:
    docker:
      # the primary container, where your job's commands are run
      - image: nlescjcer/champ_docker:devel
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
