dist: trusty

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cmake
      - cmake-data
      - gfortran
      - libblas-dev
      - liblapack-dev
      - openmpi-bin
      - libopenmpi-dev
      

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
      
install:
- cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=gfortran
- cmake --build build -- -j2 
