sudo: false

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - cmake

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
      
install:
- cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=gfortran
- cmake --build build -- -j2 

  
