#!/bin/bash

MPIFC='mpiifort'    # OR 'mpiifx'   Intel's LLVM based compiler

 cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpiifort -DENABLE_TREXIO=ON \
   -DTREXIO_LIBRARY=/software/libraries/trexio/latest/lib/libtrexio.so \
   -DTREXIO_INCLUDE_DIR=/software/libraries/trexio/latest/include/ -DENABLE_QMCKL=OFF 

cmake --build build -j

