#!/bin/bash

for file in $(ls -d *.f); do
	#echo $file;
	~/refac/refac/check_use.py $file m_common.f90
	# ~/refac/refac/clean_use.py $file -ow
	# cd ../../build
	# make
	# ([ $? -eq 0 ] && echo "success") || exit $?
	# cd ../src/vmc
done
