#!/bin/bash


include_name=pcm_3dgrid.h
module_name=pcm_3dgrid
for file in $(grep -l -F pcm_3dgrid.h *.f*); do
	echo $file $include_name $module_name;
	~/refac/refac/replace_include_by_module.py $file $include_name m_common.f90 $module_name -ow
	~/refac/refac/clean_use.py $file -ow
	
	#cd ../../build
	#make
	#([ $? -eq 0 ] && echo "success") || exit $?
	#cd ../src/vmc
done
