#!/bin/bash

VARNAME=$1
NEWMOD=$2

for f in *.f*
do
    echo $f
    python ~/roquefort/roquefort/refac_fortran.py --action move_var \
    --var_name $VARNAME --new_module $NEWMOD --filename $f -ow
done
