name: CHAMP release build with Intel

on:
  push:
    branches:
      - 'releases/**'
      - main
    tags:
      - v2.*.*
      - v3.*.*
  pull_request:
    branches:
      - 'releases/**'
      - main
  workflow_dispatch:

jobs:
  build_champ:
    strategy:
      matrix:
        toolchain: ['intel']
    name: Build CHAMP with ${{ matrix.toolchain }} OneAPI GitHub-hosted runner
    runs-on: ubuntu-latest
    timeout-minutes: 180
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
      - name: Use Intel oneAPI GitHub Actions fast setup
        uses: neelravi/intel-oneapi-github-actions@v2.0.0
        with:
          components: fortran,cpp,mpi,mkl

      - name: Get the CHAMP code
        uses: actions/checkout@v4

      - name: Compile the CHAMP code using Intel and run all tests
        run: |
          source /opt/intel/oneapi/setvars.sh

          cmake --version
          ifx --version
          icx --version
          mpiifx --version
          mpiicx --version

          cmake -H. -Bbuild \
            -DCMAKE_Fortran_COMPILER=mpiifort \
            -DCMAKE_C_COMPILER=mpiicx \
            -DBLA_STATIC=ON \
            -DBLA_VENDOR=Intel10_64lp_seq \
            -DENABLE_TREXIO=OFF \
            -DENABLE_QMCKL=OFF \

          cmake --build build -- -j2
          cd build
          ctest --output-on-failure --verbose -LE "(TREXIO|QMCKL)"
