name: Intel OneAPI build

on:
  push:
    branches: [new-parser, merging-parser, refac-problematic]
  pull_request:
    branches: [new-parser, merging-parser, refac-problematic]
jobs:
  build_intel_champ_fparser:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup repo
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
    - name: install
      run: |
        sudo apt-get install -y intel-oneapi-common-vars
        sudo apt-get install -y intel-oneapi-compiler-fortran
        sudo apt-get install -y intel-oneapi-mkl
        sudo apt-get install -y intel-oneapi-mpi
        sudo apt-get install -y intel-oneapi-mpi-devel

    - name: Compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        which mpiifort
        which mpirun
        cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpiifort
        cmake --build build -- -j1

    - name: "Test 01 (Butadiene) VMC only on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/no_optimization

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_only.inp  -o vmc_only.out  -e error_vmc_only

        echo "Comparing the energy with the reference one (total E = -26.2099365) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_only.out "total E" -26.2099365

    - name: "Test 02 (Butadiene) VMC only on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/no_optimization

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_only.inp  -o vmc_only.out  -e error_vmc_only

        echo "Comparing the energy with the reference one (total E = -26.2023287) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_only.out "total E" -26.2023287

    - name: "Test 03 (Butadiene) VMC optimization all using sr_n (500 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/optimize_wf_ci_jastrow_orb

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization.inp  -o vmc_optimization.out  -e error_vmc_optimization > screen

        echo "Comparing the energy with the reference one (total E = -26.1992624) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization.out "total E" -26.1992624

    - name: "Test 04 (Butadiene) VMC optimization all using sr_n (500 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/optimize_wf_ci_jastrow_orb

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization.inp  -o vmc_optimization.out  -e error_vmc_optimization > screen

        echo "Comparing the energy with the reference one (total E = -26.1636431) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization.out "total E" -26.1636431

    - name: "Test 05 (Butadiene) VMC optimization including geometry and csfmap using sr_n (500 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/optimize_wf_ci_jastrow_orb_and_geometry

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_sr_opt_geom.inp  -o vmc_sr_opt_geom.out  -e error_vmc_sr_opt_geom

        echo "Comparing the energy with the reference one (total E = -25.6158039) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_sr_opt_geom.out "total E" -25.6158039

    - name: "Test 06 (Butadiene) VMC optimization including geometry and csfmap using sr_n (500 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc/optimize_wf_ci_jastrow_orb_and_geometry

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_sr_opt_geom.inp  -o vmc_sr_opt_geom.out  -e error_vmc_sr_opt_geom

        echo "Comparing the energy with the reference one (total E = -25.2472141) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_sr_opt_geom.out "total E" -25.2472141

    - name: "Test 07 (Butadiene) DMC on 1 processor"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC single core"
        cd tests/CI_test/new-parser-workload/new-parser-workload-dmc/butadiene_500_DMC_pablo

        echo "Running the dmc.mov1 on one processor"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_single_core.out  -e dmc_single_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.3320038) "
        $HOME/work/champ/champ/tools/compare_value.py dmc_single_core.out "total energy (  100)" -26.3320038

    - name: "Test 08 (Butadiene) DMC on 2 processors"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC two cores"
        cd tests/CI_test/new-parser-workload/new-parser-workload-dmc/butadiene_500_DMC_pablo

        echo "Running the dmc.mov1 on two processors"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_double_core.out  -e dmc_double_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.3187227) "
        $HOME/work/champ/champ/tools/compare_value.py dmc_double_core.out "total energy (  100)" -26.3187227

    - name: "Test 09 (Butadiene) Workload DMC on 1 processor"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC from workload single core"
        cd tests/CI_test/new-parser-workload/new-parser-workload-dmc/butadiene_cipsi500_T_DMC

        echo "Running the dmc.mov1 on one processor"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_workload_single.out  -e dmc_single_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.2963582) "
        $HOME/work/champ/champ/tools/compare_value.py dmc_workload_single.out "total energy (  100)" -26.2963582

    - name: "Test 10 (Butadiene) Workload DMC on 2 processors"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC  from workload two cores"
        cd tests/CI_test/new-parser-workload/new-parser-workload-dmc/butadiene_cipsi500_T_DMC

        echo "Running the dmc.mov1 on two processors"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_workload_double.out  -e dmc_double_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.2894638) "
        $HOME/work/champ/champ/tools/compare_value.py dmc_workload_double.out "total energy (  100)" -26.2894638

    - name: "Test 11 (Butadiene) Workload VMC optimization all using sr_n (500 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi500_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_500.inp  -o vmc_optimization_500.out  -e error_vmc_optimization_500

        echo "Comparing the energy with the reference one (total E = -26.2048171) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_500.out "total E" -26.2048171

    - name: "Test 12 (Butadiene) Workload VMC optimization all using sr_n (500 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi500_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_500.inp  -o vmc_optimization_500.out  -e error_vmc_optimization_500

        echo "Comparing the energy with the reference one (total E = -26.2032228) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_500.out "total E" -26.2032228

    - name: "Test 13 (Butadiene) Workload VMC optimization all using sr_n (5000 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi5k_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_5000.inp  -o vmc_optimization_5000.out  -e error_vmc_optimization_5000

        echo "Comparing the energy with the reference one (total E = -26.1991674) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_5000.out "total E" -26.1991674

    - name: "Test 14 (Butadiene) Workload VMC optimization all using sr_n (5000 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi5k_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_5000.inp  -o vmc_optimization_5000.out  -e error_vmc_optimization_5000

        echo "Comparing the energy with the reference one (total E = -26.2166306) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_5000.out "total E" -26.2166306

    - name: "Test 15 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000.inp  -o vmc_optimization_15000.out  -e error_vmc_optimization_15000

        echo "Comparing the energy with the reference one (total E = -26.2406578) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_15000.out "total E" -26.2406578

    - name: "Test 16 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000.inp  -o vmc_optimization_15000.out  -e error_vmc_optimization_15000

        echo "Comparing the energy with the reference one (total E = -26.2371252) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_15000.out "total E" -26.2371252

    - name: "Test 17 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants with 3body Jastrow) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF_3body

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000_3body.inp  -o vmc_optimization_15000_3body.out  -e error_vmc_optimization_15000_3body

        echo "Comparing the energy with the reference one (total E = -26.2212718) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_15000_3body.out "total E" -26.2212718

    - name: "Test 18 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants with 3body Jastrow) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF_3body

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000_3body.inp  -o vmc_optimization_15000_3body.out  -e error_vmc_optimization_15000_3body

        echo "Comparing the energy with the reference one (total E = -26.2166595) "
        $HOME/work/champ/champ/tools/compare_value.py vmc_optimization_15000_3body.out "total E" -26.2166595


    - name: "Test 19 (H2) sto basis optimize jastrow sr_n method on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc.inp -o revised_vmc_single.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0084981) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_single.out "total E" -1.0084981

    - name: "Test 20 (H2) sto basis optimize jastrow sr_n method on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc.inp -o revised_vmc_double.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0093392) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_double.out "total E" -1.0093392

    - name: "Test 21 (H2) sto basis optimize wf+jastrow using lin_d method on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc_davidson_check.inp -o revised_vmc_davidson_check_single.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0549647) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_davidson_check_single.out "total E" -1.0549647

    - name: "Test 22 (H2) sto basis optimize wf+jastrow using lin_d method on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc_davidson_check.inp -o revised_vmc_davidson_check_double.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0569553) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_davidson_check_double.out "total E" -1.0569553

    - name: "Test 23 (H2) sto basis optimize wf+jastrow using lin_d method nopt_iter=20 on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc_lin.inp -o revised_vmc_lin_single.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0549647) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_davidson_check_single.out "total E" -1.0549647

    - name: "Test 24 (H2) sto basis optimize wf+jastrow using lin_d method nopt_iter=20  on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-h2

        echo "Running the optimization calculation"
        /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_vmc_lin.inp -o revised_vmc_lin_double.out -e error

        echo "Comparing the energy with the reference one (total E = -1.0569553) "
        $HOME/work/champ/champ/tools/compare_value.py revised_vmc_davidson_check_double.out "total E" -1.0569553


    # Tests about psb3

    # - name: "Test 19 (psb3) optimize wavefunction and ci using sr_n (400 determinants, 2 states, csfmap) on 1 processor"
    #   run: |
    #     echo "Running the tests using the new parser. Butadiene VMC "
    #     cd tests/CI_test/new-parser-psb3

    #     echo "Running the optimization calculation"
    #     /opt/intel/oneapi/mpi/latest/bin/mpirun -np 1  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_sr_n.inp -o revised_sr_n_single.out -e error

    #     echo "Comparing the energy with the reference one (total E = -42.5485250) "
    #     $HOME/work/champ/champ/tools/compare_value.py revised_sr_n_single.out "total E" -42.5485250

    # - name: "Test 20 (psb3) optimize wavefunction and ci using sr_n (400 determinants, 2 states, csfmap) on 2 processors"
    #   run: |
    #     echo "Running the tests using the new parser. Butadiene VMC "
    #     cd tests/CI_test/new-parser-psb3

    #     echo "Running the optimization calculation"
    #     /opt/intel/oneapi/mpi/latest/bin/mpirun -np 2  $HOME/work/champ/champ/bin/vmc.mov1 -i revised_sr_n.inp -o revised_sr_n_double.out -e error

    #     echo "Comparing the energy with the reference one (total E = -42.6209550) "
    #     $HOME/work/champ/champ/tools/compare_value.py revised_sr_n_double.out "total E" -42.6209550
