name: Intel OneAPI build

on:
  push:
    branches: [new-parser, merging-parser, refac-problematic]
  pull_request:
    branches: [new-parser, merging-parser, refac-problematic]
jobs:
  build_intel_champ_fparser:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup repo
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update 
    - name: install
      run: |
        sudo apt-get install -y intel-oneapi-common-vars
        sudo apt-get install -y intel-oneapi-compiler-fortran
        sudo apt-get install -y intel-oneapi-mkl 
        sudo apt-get install -y intel-oneapi-mpi 
        sudo apt-get install -y intel-oneapi-mpi-devel         
        
    - name: Compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        echo $PATH
        which ifort 
        ifort --version
        which mpirun
        mpirun --version
        ls -l /opt/intel/oneapi/mpi/latest/bin/*
        cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=/opt/intel/oneapi/mpi/latest/bin/mpiifort
        cmake --build build -- -j1