name: CHAMP-EU CI - Docker image build and tagging for Docker Hub

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'tools/trex_tools/**'
      - '**.md'
      - '.github/workflows/build_documentation_devel.yml'
      - '.github/workflows/test_python.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'tools/trex_tools/**'
      - '**.md'
      - '.github/workflows/build_documentation_devel.yml'
      - '.github/workflows/test_python.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Build the Docker image
      run: |
        docker build . --file docker/GNU/Dockerfile --tag champ-gnu-${{ github.sha }}:latest
        docker tag champ-gnu-${{ github.sha }}:latest champ-gnu-${{ github.sha }}:$(echo ${{ github.sha }} | cut -c1-7)
