name: Self-hosted Intel OneAPI build

on:
  push:
    branches: [new-parser, merging-parser, refac-problematic]
  pull_request:
    branches: [new-parser, merging-parser, refac-problematic]
jobs:
  build_intel_champ_fparser:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpiifort
        cmake --build build -- -j2
        echo "Build using Intel oneAPI compilers is sucessfull"


    - name: "Test 01 (Butadiene) VMC only on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the calculation"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_only.inp  -o vmc_only.out  -e error_vmc_only

        echo "Comparing the energy with the reference one (total E = -26.2099365) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_only.out "total E" -26.2099365

    - name: "Test 02 (Butadiene) VMC only on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the calculation"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_only.inp  -o vmc_only.out  -e error_vmc_only

        echo "Comparing the energy with the reference one (total E = -26.2023287) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_only.out "total E" -26.2023287

    - name: "Test 03 (Butadiene) VMC optimization all using sr_n (500 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization.inp  -o vmc_optimization.out  -e error_vmc_optimization > screen

        echo "Comparing the energy with the reference one (total E = -26.1992624) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization.out "total E" -26.1992624

    - name: "Test 04 (Butadiene) VMC optimization all using sr_n (500 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-butadiene-vmc

        echo "Copy an initial mc configuration for reference"
        cp -v mc_configs_start_save mc_configs_start

        echo "Running the optimization calculation"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization.inp  -o vmc_optimization.out  -e error_vmc_optimization > screen

        echo "Comparing the energy with the reference one (total E = -26.1636431) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization.out "total E" -26.1636431

    - name: "Test 05 (Butadiene) DMC on 1 processor"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC single core"
        cd tests/CI_test/new-parser-butadiene-dmc

        echo "Running the dmc.mov1 on one processor"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_single_core.out  -e dmc_single_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.3320038) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py dmc_single_core.out "total energy (  100)" -26.3320038

    - name: "Test 06 (Butadiene) DMC on 2 processors"
      run: |
        echo "Running the DMC tests using the new parser. Butadiene DMC two cores"
        cd tests/CI_test/new-parser-butadiene-dmc

        echo "Running the dmc.mov1 on two processors"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/dmc.mov1 -i dmc.inp  -o dmc_double_core.out  -e dmc_double_core.error

        echo "Comparing the energy with the reference one (total energy (  100) = -26.3187227) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py dmc_double_core.out "total energy (  100)" -26.3187227

    - name: "Test 07 (Butadiene) Workload VMC optimization all using sr_n (500 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi500_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_500.inp  -o vmc_optimization_500.out  -e error_vmc_optimization_500

        echo "Comparing the energy with the reference one (total E = -26.2048171) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_500.out "total E" -26.2048171

    - name: "Test 08 (Butadiene) Workload VMC optimization all using sr_n (500 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi500_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_500.inp  -o vmc_optimization_500.out  -e error_vmc_optimization_500

        echo "Comparing the energy with the reference one (total E = -26.2032228) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_500.out "total E" -26.2032228

    - name: "Test 09 (Butadiene) Workload VMC optimization all using sr_n (5000 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi5k_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_5000.inp  -o vmc_optimization_5000.out  -e error_vmc_optimization_5000

        echo "Comparing the energy with the reference one (total E = -26.1991674) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_5000.out "total E" -26.1991674

    - name: "Test 10 (Butadiene) Workload VMC optimization all using sr_n (5000 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi5k_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_5000.inp  -o vmc_optimization_5000.out  -e error_vmc_optimization_5000

        echo "Comparing the energy with the reference one (total E = -26.2166306) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_5000.out "total E" -26.2166306

    - name: "Test 11 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants) on 1 processor"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 1  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000.inp  -o vmc_optimization_15000.out  -e error_vmc_optimization_15000

        echo "Comparing the energy with the reference one (total E = -26.2406578) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_15000.out "total E" -26.2406578

    - name: "Test 12 (Butadiene) Workload VMC optimization all using sr_n (15000 determinants) on 2 processors"
      run: |
        echo "Running the tests using the new parser. Butadiene VMC "
        cd tests/CI_test/new-parser-workload/new-parser-workload-vmc/butadiene_cipsi15k_T_optWF

        echo "Running the optimization calculation"
        mpirun -np 2  /home/ravindra/actions-runner/_work/champ/champ/bin/vmc.mov1 -i vmc_optimization_15000.inp  -o vmc_optimization_15000.out  -e error_vmc_optimization_15000

        echo "Comparing the energy with the reference one (total E = -26.2371252) "
        /home/ravindra/actions-runner/_work/champ/champ/tools/compare_value.py vmc_optimization_15000.out "total E" -26.2371252


