name: Self-hosted Intel OneAPI Build and Testing on ccpgate/ccp01

on:
  push:
    branches:
      - 'releases/**'
      - main
      - feature/debug-ci
      - optimization
      - champ-ortho-merge
    # Sequence of patterns matched against refs/tags
    tags:
      - v2.*.*
  pull_request:
    branches:
      - 'releases/**'
      - main
      - champ-ortho-merge
      - cartesian_d_qmckl
      - optimization
      - feature/debug-ci

jobs:
  build_champ:
    strategy:
      matrix:
        toolchain: ['intel']
    name: Build CHAMP with ${{ matrix.toolchain }} OneAPI self-hosted runner ccpgate/ccp01
    runs-on: self-hosted
    timeout-minutes: 180
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
    - uses: actions/checkout@v2
    - name: Compile the CHAMP code using Intel and run tests using ctest
      if: matrix.toolchain == 'intel'
      run: |
        export MODULEPATH=${MODULEPATH}:/software/intel/oneapi/modulefiles:/software/libraries/Modulefiles
        module avail
        module load compiler-rt/latest
        module load compiler/latest
        module load icc/latest
        module load mkl/latest
        module load mpi/latest
        module load python3/latest
        module load cmake/3.22.1-intel
        module load hdf5/1.14.1-intel
        module load trexio/2.3.0-intel

        which mpirun
        export LD_LIBRARY_PATH=/software/intel/oneapi/mkl/latest/lib/intel64:/software/intel/oneapi/mpi/latest/lib:/software/intel/oneapi/intelpython/python3.7/lib:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=/home/filippi/lib:/software/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin:$LD_LIBRARY_PATH
        export LD_RUN_PATH=/home/filippi/lib:/software/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin:/software/intel/oneapi/mkl/latest/lib/intel64:$LD_RUN_PATH
        cmake --version
        cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpiifort -DCMAKE_C_COMPILER=mpiicc -DBLA_STATIC=ON -DBLA_VENDOR=Intel10_64lp -DENABLE_TREXIO=ON -DTREXIO_LIBRARY=/software/trexio/lib/libtrexio.so -DTREXIO_INCLUDE_DIR=/software/trexio/include/ -DHDF5_LIBRARIES=/software/hdf5/1.14.1/lib/libhdf5.so -DHDF5_INCLUDE_DIRS=/software/hdf5/1.14.1/include
        cmake --build build -- -j8
        cd build
        ctest --output-on-failure --verbose


    - name: Compile the CHAMP code and run tests using ctest
      if: matrix.toolchain == 'gnu'
      run: |
        export MODULEPATH=${MODULEPATH}:/software/intel/oneapi/modulefiles:/software/libraries/Modulefiles
        module avail
        module load compiler-rt/latest
        module load compiler/latest
        module load icc/latest
        module load mkl/latest
        module load mpi/latest
        module load python3/latest
        module load cmake
        module load hdf5
        module load trexio

        which mpirun
        cmake --version
        export OMPI_FC=gfortran-11
        cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DVECTORIZED=no -DENABLE_TREXIO=ON -DTREXIO_LIBRARY=/software/trexio/lib/libtrexio.so -DTREXIO_INCLUDE_DIR=/software/trexio/include/
        cmake --build build -- -j2
        cd build
        ctest --output-on-failure --verbose

    - name: "Zip the test reults"
      run: |
        echo "Compressing the test results from workflow"
        cd tests/
        tar -czvf workflow_artifacts.tar.gz CI_test/*/*_core_?.out 

    - name: "Upload calculation result artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: results-workflow-actions
        path: tests/workflow_artifacts.tar.gz
        retention-days: 30



