name: Build and test  

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install_compilers_and_libraries 
      run: |
           sudo apt install gfortran libmkl-full-dev openmpi-bin gawk openmpi-bin libblas-dev liblapack-dev 
           gawk --version

    - name: Building_code
      run: |
           cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl
           cmake --build build -- -j2

    - name: Testing_code
      run: |  
           cp ./tests/psb3_cas66/include/* ./src/include 
           cat ./tests/psb3_cas66/include/sr.h | sed s/80000/10000/g > ./src/include/sr.h
           cd build  
           make -j
           cd ../tests/psb3_cas66
           pwd
           cat ../../src/include/sr.h | grep MPARM  
           ../../bin/vmc.mov1 < sr_n.inp 
# Testing
#    - name: Test code with python script 
#      run: conda install numpy
# -DBLAS_blas_LIBRARY=/usr/share/miniconda/pkgs/libcblas-3.8.0-14_openblas/lib/libopenblasp-r0.3.7.so