name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - run: conda --version

    - name: Install_compilers_and_libraries
      run: |
           sudo apt install gfortran openmpi-bin gawk libblacs-mpi-dev liblapack-dev # valgrind libmkl-full-dev
           gawk --version
           mpirun --version

    - name: Building_code_for_h2
      run: |

           # save the module file
           cp src/vmc/m_vmc.f90 ./m_vmc_save
           cp src/vmc/m_sr.f90 ./m_sr_save
           cp src/vmc/m_optci.f90 ./m_optci_save

           # copy module file
           cp tests/CI_test/h2/module/*.f90 src/vmc

           # compile
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DENABLE_TEST=ON
           cmake --build build -- -j2

    - name: Run_h2
      run: |

           cd tests/CI_test/h2/qmc_1det/
           #export OMPI_MCA_btl=^openib # Avoids MCA warnings

           # run and compare simple sampling
           echo "- Running vmc.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < vmc.inp > vmc.out 
           echo "  total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc.out "total E" -1.0083658 

           # run and compare simple sampling MPI
           echo "- Running vmc.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < vmc.inp > vmc.out 
           echo "  total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc.out "total E" -1.0119453 
           #$HOME/work/champ/champ/tools/compare_output_file.py vmc.out output_ref/vmc_2_threads.out

           # run and compare simple sampling
           echo "- Running vmc_lin.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < vmc_lin.inp > vmc_lin.out 
           echo "  total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc_lin.out "total E" -1.0604737

           # run and compare simple sampling MPI
           echo "- Running vmc_lin.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < vmc_lin.inp > vmc_lin.out 
           echo "  total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc_lin.out "total E" -1.0586750 
           #$HOME/work/champ/champ/tools/compare_output_file.py vmc_lin.out output_ref/vmc_lin_2_threads.out
           
           # restore the module files
           cd $HOME/work/champ/champ
           cp m_vmc_save ./src/vmc/m_vmc.f90
           cp m_optci_save ./src/vmc/m_optci.f90
           cp m_sr_save ./src/vmc/m_sr.f90

    - name: Building_code_for_psb3
      run: |

           # save the module files
           cp src/vmc/m_vmc.f90 ./m_vmc_save
           cp src/vmc/m_sr.f90 ./m_sr_save
           cp src/vmc/m_optci.f90 ./m_optci_save

           # copy module files to src
           cp tests/CI_test/psb3/module/*.f90 src/vmc

           # compile
           rm -rf bin build
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DENABLE_TEST=ON
           cmake --build build --clean-first -- -j2

    - name: Run_psb3
      run: |

           cd tests/CI_test/psb3/

           # run and compare a sr calculation
           echo "Running sr_n.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < sr_n.inp > sr_n.out
           echo "total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py sr_n.out "total E" -42.7144606 

           # run and compare a sr calculation MPI
           echo "Running sr_n.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < sr_n.inp > sr_n.out
           echo "total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py sr_n.out "total E" -42.6476514 
           #$HOME/work/champ/champ/tools/compare_output_file.py sr_n.out output_ref/sr_n_2_threads.out
           
           # run and compare a regterg calculation
           echo "Running regterg.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < regterg.inp > regterg.out 
           echo "total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py regterg.out "total E" -41.4910248 

           # run and compare a regterg calculation MPI
           echo "Running regterg.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < regterg.inp > regterg.out 
           echo "total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py regterg.out "total E" -41.3989435 
           #$HOME/work/champ/champ/tools/compare_output_file.py regterg.out output_ref/regterg_2_threads.out

           # run and compare a Davidson calculation
           echo "Running free.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < free.inp > free.out 
           echo "first eigenvalue vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py free.out "eigenvalue            1" -45.898315302789705 

           # run and compare a Davidson calculation MPI
           echo "Running free.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < free.inp > free.out 
           echo "first eigenvalue vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py free.out "eigenvalue            1" -50.713234670513742 
           #$HOME/work/champ/champ/tools/compare_output_file.py free.out output_ref/free_2_threads.out
           
           # run and compare a optimize all (ci, jas, orb) calculation
           echo "Running vmc_optall.inp in serial:"
           $HOME/work/champ/champ/bin/vmc.mov1 < vmc_optall.inp > vmc_optall.out  
           echo "total E vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc_optall.out "total E" -22.4869109

           # run and compare a optimize all (ci, jas, orb) calculation MPI
           echo "Running vmc_optall.inp in parallel:"
           mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < vmc_optall.inp > vmc_optall.out 
           echo "first eigenvalue vs reference:" 
           $HOME/work/champ/champ/tools/compare_value.py vmc_optall.out "total E" -21.6147339 
           #$HOME/work/champ/champ/tools/compare_output_file.py vmc_optall.out output_ref/vmc_optall_2_threads.out
           #  restore the module files
           
           cd $HOME/work/champ/champ
           cp m_vmc_save ./src/vmc/m_vmc.f90
           cp m_optci_save ./src/vmc/m_optci.f90
           cp m_sr_save ./src/vmc/m_sr.f90

