name: Build and test  

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: conda --version 

    - name: Install_compilers_and_libraries 
      run: |
           sudo apt install gfortran libmkl-full-dev openmpi-bin gawk openmpi-bin libblas-dev liblapack-dev # valgrind
           gawk --version

    - name: Building_code_for_h2
      run: |
           cp src/vmc/m_vmc.f90 ./m_vmc_save
           cp src/vmc/m_sr.f90 ./m_sr_save
           cp src/vmc/m_optci.f90 ./m_optci_save

           cp tests/CI_test/h2/*.f90 src/vmc
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl -DENABLE_TEST=ON
           cmake --build build -- -j2

    - name: Run_H2
      run: |
           cd tests/CI_test/h2/qmc_1det/
           ../../../../bin/vmc.mov1 < vmc.inp > vmc.out
           ../../../../bin/vmc.mov1 < vmc_lin.inp > vmc_lin.out
           cd ../../../../
           cp m_vmc_save ./src/vmc/m_vmc.f90
           cp m_optci_save ./src/vmc/m_optci.f90
           cp m_sr_save ./src/vmc/m_sr.f90

# To be tested:
#      cd build/tests/CI_test && mpirun -s all -np 2 ../../bin/vmc.mov1  < sr_n.inp
#    - name: Test parallel
#      run: |  
#           echo running sr_n.inp
#           cd ./tests/CI_test
#           mpirun --version
#           cp ../../bin/vmc.mov1  ./
#           mpirun  -np 2  ./vmc.mov1  < sr_n.inp 
#
#           mpirun -np 2 ../../bin/vmc.mov1  < regterg.inp  
#           mpirun -np 2 ../../bin/vmc.mov1  < free.inp
#           mpirun -np 2 ../../bin/vmc.mov1  < vmc_optall.inp
