name: Build and test  

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Conda installation 
      uses: s-weigand/setup-conda@master
      with:
        update-conda: true
        python-version: 3.7
        conda-channels: anaconda, conda-forge

    - run: conda --version 
    - run: which python

    - name: Install compilers and libraries 
      run: |
           conda install libgfortran openmpi-mpifort blas
           sudo apt-get install gawk
           gawk --version 

    - name: Building code  
      env:
           CONDA_PREFIX: /usr/share/miniconda
      run: |  
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort 
    - name: list folders
      run: ls -ltRh /usr/share/miniconda 
        # -DBLAS_blas_LIBRARY=/home/plopez/Programs/BLAS-3.8.0/blas_LINUX.a
#           cmake --build build  --target all -- -j4 # vmc.mov1 -- -j4
# Testing
#    - name: Test code with python script 
#      run: conda install numpy