name: Build and test  

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: conda --version 

    - name: Install_compilers_and_libraries 
      run: |
           sudo apt install gfortran libmkl-full-dev openmpi-bin gawk openmpi-bin libblas-dev liblapack-dev # valgrind
           gawk --version

    - name: Building_code
      run: |
           cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl
           cmake --build build -- -j2

    - name: Building_code_for_testing
      run: |  
           ulimit -s unlimited
           cp ./tests/psb3_cas66/include/* ./src/include 
           cat ./tests/psb3_cas66/include/sr.h | sed -e s/"MCONF\=80000"/"MCONF\=10000"/g > ./src/include/sr.h
           cat ./tests/psb3_cas66/include/optci.h | sed -e s/"MXCITERM\=4600"/"MXCITERM\=600"/g -e s/"MXCIREDUCED\=2000"/"MXCIREDUCED=10"/g > ./src/include/optci.h
           cd build  
           make -j

    - name: Test sr_n
      run: |  
           cd ../tests/psb3_cas66
           ../../bin/vmc.mov1 < sr_n.inp

    - name: Test regterg
      run: |  
           ../../bin/vmc.mov1 < regterg.inp
           
    - name: Test free
      run: |  
           ../../bin/vmc.mov1 < free.inp 

    - name: Test vmc_optall
      run: |  
           cd ../butadiene-3wfs/TZ-1M-128
           ../../bin/vmc.mov1 < vmc_optall.inp
