name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: conda --version

    - name: Install_compilers_and_libraries
      run: |
           sudo apt install gfortran libmkl-full-dev openmpi-bin gawk openmpi-bin libblas-dev liblapack-dev # valgrind
           gawk --version

    - name: Building_code_for_h2
      run: |

           # save the module file
           cp src/vmc/m_vmc.f90 ./m_vmc_save
           cp src/vmc/m_sr.f90 ./m_sr_save
           cp src/vmc/m_optci.f90 ./m_optci_save

           # copy module file
           cp tests/CI_test/h2/module/*.f90 src/vmc

           # compile
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl -DENABLE_TEST=ON
           cmake --build build -- -j2

    - name: Run_h2
      run: |

           cd tests/CI_test/h2/qmc_1det/

           # run and compare simple sampling
           $HOME/work/champ/champ/bin/vmc.mov1 < vmc.inp > vmc.out
           $HOME/work/champ/champ/tools/compare_value.py vmc.out "total E" -1.0070217

           # run and compare simple sampling
           $HOME/work/champ/champ/bin/vmc.mov1 < vmc_lin.inp > vmc_lin.out
           $HOME/work/champ/champ/tools/compare_value.py vmc_lin.out "total E" -1.0584288

           # run and compare simple sampling MPI
           # mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < vmc.inp > vmc.out
           # $HOME/work/champ/champ/tools/compare_output_file.py vmc.out output_ref/vmc_ref.out

           # run and compare simple sampling MPI
           # mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < vmc_lin.inp > vmc_lin.out
           # $HOME/work/champ/champ/tools/compare_output_file.py vmc_lin.out output_ref/vmc_lin_ref.out

           # restore the module files
           cd $HOME/work/champ/champ
           cp m_vmc_save ./src/vmc/m_vmc.f90
           cp m_optci_save ./src/vmc/m_optci.f90
           cp m_sr_save ./src/vmc/m_sr.f90


    - name: Building_code_for_psb3
      run: |

           # save the module files
           cp src/vmc/m_vmc.f90 ./m_vmc_save
           cp src/vmc/m_sr.f90 ./m_sr_save
           cp src/vmc/m_optci.f90 ./m_optci_save

           # copy module files to src
           cp tests/CI_test/psb3/module/*.f90 src/vmc

           # compile
           rm -rf bin build
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl -DENABLE_TEST=ON
           cmake --build build --clean-first -- -j2

    - name: Run_psb3
      run: |

           cd tests/CI_test/psb3/

           # run and compare a sr calculation
           $HOME/work/champ/champ/bin/vmc.mov1 < sr_n.inp > sr_n.out

           # run and compare a sr calculation MPI
           # mpirun --stdin all -n 2 $HOME/work/champ/champ/bin/vmc.mov1 < sr_n.inp > sr_n.out
           # $HOME/work/champ/champ/tools/compare_output_file.py sr_n.out output_ref/sr_n_ref.out

           #  restore the module files
           cd $HOME/work/champ/champ
           cp m_vmc_save ./src/vmc/m_vmc.f90
           cp m_optci_save ./src/vmc/m_optci.f90
           cp m_sr_save ./src/vmc/m_sr.f90

