name: Build and test  

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: conda --version 

    - name: Install_compilers_and_libraries 
      run: |
           sudo apt install gfortran libmkl-full-dev openmpi-bin gawk openmpi-bin libblas-dev liblapack-dev # valgrind
           gawk --version

    - name: Building_code
      run: |
           cp ./tests/CI_test/include/* ./src/include 
           cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_PREFIX_PATH=/usr/include/mkl -DENABLE_TEST=ON
           cmake --build build -- -j2
           cd build/tests/CI_test && mpirun -s all -np 2 ../../bin/vmc.mov1  < sr_n.inp

#           cd build/tests/CI_test && ctest --verbose

#    - name: Test serial 
#
#      run: |  
#           echo running vmc_optall.inp 
#           cd ./tests/CI_test
#           echo "Running vmc_optall.inp ..."
#           ../../bin/vmc.mov1 < vmc_optall.inp
#           echo "... done!"
#
#    - name: Test parallel
#      run: |  
#           echo running sr_n.inp
#           cd ./tests/CI_test
#           mpirun --version
#           mpirun -np 2 ../../bin/vmc.mov1  < sr_n.inp 
#           mpirun -np 2 ../../bin/vmc.mov1  < regterg.inp  
#           mpirun -np 2 ../../bin/vmc.mov1  < free.inp
#           mpirun -np 2 ../../bin/vmc.mov1  < vmc_optall.inp
